import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import LetterGlitch from "@/components/LetterGlitch";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-black`}>
        <aside
          aria-hidden="true"
          className="fixed inset-0 h-screen w-screen z-0 pointer-events-none"
        >
          <LetterGlitch centerVignette className="fixed inset-0 opacity-20" />
        </aside>
        {children}
      </body>
    </html>
  );
}
